### ISSUE TITLE
Public DMP not linking to expanded version

### ISSUE THREAD

**Issue by Br-Johnson** [CDLUC3/dmptool#561]
Hi,

Within our organization we have two DMPs that have been finalized (DMP IDs: [10.48321/D18S8D](https://doi.org/10.48321/D18S8D) and [10.48321/D1794R](https://doi.org/10.48321/D1794R)). The visibility for these DMPs is 'Public' and 'Organizational' respectively. However, when viewing these DMPs, the 'Read the data management plan' link in the top-right of the page does not show up.

Is this a bug, or do we need to make adjustments to the template that we developed and that was used for these DMPs?

**Comment by briri** [comment]
Hi @Br-Johnson I haven't traced down the root cause yet for this. 

Can you please make a small change to the public DMP (e.g. add an extra blank space somewhere in the abstract) and then save, it will generate the PDF, store it, and then update the DMP record so that the download link is accessible from the landing page (this usually only takes a few seconds, but can take up to a minute or two).

We will continue to investigate to try and see what happened, but the above solution should get you by for now

**Comment by Br-Johnson** [comment]
Hey @briri I've updated and saved https://doi.org/10.48321/D18S8D but I still don't see a link to the PDF. Thanks for your help with this!

**Comment by briri** [comment]
Thanks for resubmitting @Br-Johnson.

**Comment by briri** [comment]
User updates their plan in the DMPTool. The DMPTool generates the PDF narrative document and then submits it to the DMPHub. Found the log entries in the DMPHub and can see the narrative file is added to S3 and that the URL for the document is attached to the DMP ID record. When viewing the record however, the link is no longer attached in the `dmproadmap_related_identifiers` array.

Was able to reproduce the issue with our test DMP, 10.48321/D1F301.
Need to investigate further to see if there is a subsequent update to the record that is wiping out the link back to the PDF document. 

Seems to be limited to scenarios where the DMP is being updated (as opposed to the initial registration of the DMP ID)

**Comment by timvdstap** [comment]
Just chiming in here - it still seems to be an issue, even for DMPs that are newly generated/made public: https://doi.org/10.48321/D14FA6A58E. Does it perhaps have something to do with the template being used (which is our institutional Hakai Institute Data Management Plan template)?

**Comment by mariapraetzellis** [comment]
This is the same issue as https://github.com/orgs/CDLUC3/projects/14/views/3?pane=issue&itemId=66086469

**Comment by briri** [comment]
This issue has been fixed.

**Comment by timvdstap** [comment]
Hi @briri - would that only be for newly created DMPs? Seems like the issue still persists, e.g. when I look at [this record](https://doi.org/10.48321/D1CW23)

**Comment by briri** [comment]
Hi @timvdstap, if you make a small change to the DMP it will force an update. 
All newly created DMPs, and any future updates to an existing DMP will correct the issue with the missing PDF. Please note that it can take a few minutes for the PDF to appear since it is generated asynchronously

**Comment by timvdstap** [comment]
Thank you @briri - I can confirm it works now, much appreciated :)
